stages:
  - chartName: var-echo-main
    stage: dev
    namespace: dev
    revision: main
  - chartName: var-echo-644c10f
    stage: dev
    namespace: dev
    revision: 644c10f
  - chartName: var-echo-the-same
    stage: dev
    namespace: dev
    revision: 644c10f
  - chartName: var-echo-another
    stage: dev
    namespace: dev
    revision: 953f357
  - chartName: var-echo-adujst
    stage: dev
    namespace: dev
    revision: 953f357