apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: sm-ctrl
  namespace: servicemesh
spec:
  tracing:
    type: Jaeger
    sampling: 10000
  gateways:
    openshiftRoute:
      enabled: true
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod
  version: v2.5
  mode: ClusterWide
