{{- range .Values.stages }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .chartName }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chtime/var-echo'
    targetRevision: {{ .ref }}
    path: helm
    helm:
      parameters:
        - name: chartName
          value: {{ .chartName }}
        - name: stage
          value: {{ .stage }}
        - name: namespace
          value: {{ .namespace }}
        - name: ref
          value: {{ .ref }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end}}