{{ range .Values.builds }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: var-echo-{{ .Values.revision }}
  namespace: dev
spec:
  source:
    git:
      uri: "https://github.com/chtime/var-echo"
      ref: {{ .Values.revision }}
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: "var-echo:{{ .Values.revision }}"
---
{{ end }}