{{- range .stages }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dynamic-stage-{{ .name }}
  namespace: ds
spec:
  host: dynamic-stage-{{ .name }}.apps-crc.testing
  port:
    targetPort: http
  tls:
    termination: edge 
  to:
    kind: Service
    name: dynamic-stage-{{ .name }}
    weight: 100
---
{{- end }}
