apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: var-echo-charts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chtime/byi-oc'
    targetRevision: master
    path: apps/var-echo-charts
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
